delete from Activo
delete from Carrito
delete from Valor
delete from Producto
delete from SubCategoria_Propiedad
delete from Propiedad
delete from SubCategoria
delete from Categoria
delete from Imagen
delete from MetodoDePago
delete from PayPal
delete from Producto_Carrito
delete from Producto_Tag
delete from Producto_Usuario
delete from Sucursal
delete from Tag
delete from Tarjeta
delete from Tienda
delete from Usuario
delete from Valor
delete from Vendido