<?xml version="1.0" encoding="utf-8"?>
<Database Name="Armazon" Class="ArmazonDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\Armazon.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ArmazonConnectionString" Provider="System.Data.SqlClient" />
</Database>