#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Armazon
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="Armazon")]
	public partial class ArmazonDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertActivo(Activo instance);
    partial void UpdateActivo(Activo instance);
    partial void DeleteActivo(Activo instance);
    partial void InsertVendido(Vendido instance);
    partial void UpdateVendido(Vendido instance);
    partial void DeleteVendido(Vendido instance);
    partial void InsertCarrito(Carrito instance);
    partial void UpdateCarrito(Carrito instance);
    partial void DeleteCarrito(Carrito instance);
    partial void InsertCategoria(Categoria instance);
    partial void UpdateCategoria(Categoria instance);
    partial void DeleteCategoria(Categoria instance);
    partial void InsertMetodoDePago(MetodoDePago instance);
    partial void UpdateMetodoDePago(MetodoDePago instance);
    partial void DeleteMetodoDePago(MetodoDePago instance);
    partial void InsertProducto(Producto instance);
    partial void UpdateProducto(Producto instance);
    partial void DeleteProducto(Producto instance);
    partial void InsertProducto_Carrito(Producto_Carrito instance);
    partial void UpdateProducto_Carrito(Producto_Carrito instance);
    partial void DeleteProducto_Carrito(Producto_Carrito instance);
    partial void InsertProducto_Tag(Producto_Tag instance);
    partial void UpdateProducto_Tag(Producto_Tag instance);
    partial void DeleteProducto_Tag(Producto_Tag instance);
    partial void InsertProducto_Usuario(Producto_Usuario instance);
    partial void UpdateProducto_Usuario(Producto_Usuario instance);
    partial void DeleteProducto_Usuario(Producto_Usuario instance);
    partial void InsertPropiedad(Propiedad instance);
    partial void UpdatePropiedad(Propiedad instance);
    partial void DeletePropiedad(Propiedad instance);
    partial void InsertSubCategoria(SubCategoria instance);
    partial void UpdateSubCategoria(SubCategoria instance);
    partial void DeleteSubCategoria(SubCategoria instance);
    partial void InsertSubCategoria_Propiedad(SubCategoria_Propiedad instance);
    partial void UpdateSubCategoria_Propiedad(SubCategoria_Propiedad instance);
    partial void DeleteSubCategoria_Propiedad(SubCategoria_Propiedad instance);
    partial void InsertSucursal(Sucursal instance);
    partial void UpdateSucursal(Sucursal instance);
    partial void DeleteSucursal(Sucursal instance);
    partial void InsertTag(Tag instance);
    partial void UpdateTag(Tag instance);
    partial void DeleteTag(Tag instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertUsuario_Tag(Usuario_Tag instance);
    partial void UpdateUsuario_Tag(Usuario_Tag instance);
    partial void DeleteUsuario_Tag(Usuario_Tag instance);
    partial void InsertValor(Valor instance);
    partial void UpdateValor(Valor instance);
    partial void DeleteValor(Valor instance);
    #endregion
		
		public ArmazonDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ArmazonConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ArmazonDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ArmazonDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ArmazonDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ArmazonDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Activo> Activos
		{
			get
			{
				return this.GetTable<Activo>();
			}
		}
		
		public System.Data.Linq.Table<Vendido> Vendidos
		{
			get
			{
				return this.GetTable<Vendido>();
			}
		}
		
		public System.Data.Linq.Table<Carrito> Carritos
		{
			get
			{
				return this.GetTable<Carrito>();
			}
		}
		
		public System.Data.Linq.Table<Categoria> Categorias
		{
			get
			{
				return this.GetTable<Categoria>();
			}
		}
		
		public System.Data.Linq.Table<MetodoDePago> MetodoDePagos
		{
			get
			{
				return this.GetTable<MetodoDePago>();
			}
		}
		
		public System.Data.Linq.Table<Producto> Productos
		{
			get
			{
				return this.GetTable<Producto>();
			}
		}
		
		public System.Data.Linq.Table<Producto_Carrito> Producto_Carritos
		{
			get
			{
				return this.GetTable<Producto_Carrito>();
			}
		}
		
		public System.Data.Linq.Table<Producto_Tag> Producto_Tags
		{
			get
			{
				return this.GetTable<Producto_Tag>();
			}
		}
		
		public System.Data.Linq.Table<Producto_Usuario> Producto_Usuarios
		{
			get
			{
				return this.GetTable<Producto_Usuario>();
			}
		}
		
		public System.Data.Linq.Table<Propiedad> Propiedads
		{
			get
			{
				return this.GetTable<Propiedad>();
			}
		}
		
		public System.Data.Linq.Table<SubCategoria> SubCategorias
		{
			get
			{
				return this.GetTable<SubCategoria>();
			}
		}
		
		public System.Data.Linq.Table<SubCategoria_Propiedad> SubCategoria_Propiedads
		{
			get
			{
				return this.GetTable<SubCategoria_Propiedad>();
			}
		}
		
		public System.Data.Linq.Table<Sucursal> Sucursals
		{
			get
			{
				return this.GetTable<Sucursal>();
			}
		}
		
		public System.Data.Linq.Table<Tag> Tags
		{
			get
			{
				return this.GetTable<Tag>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<Usuario_Tag> Usuario_Tags
		{
			get
			{
				return this.GetTable<Usuario_Tag>();
			}
		}
		
		public System.Data.Linq.Table<Valor> Valors
		{
			get
			{
				return this.GetTable<Valor>();
			}
		}
	}
	
	[Table(Name="dbo.Activo")]
	public partial class Activo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CarritoID;
		
		private int _UsuarioID;
		
		private EntityRef<Carrito> _Carrito;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCarritoIDChanging(int value);
    partial void OnCarritoIDChanged();
    partial void OnUsuarioIDChanging(int value);
    partial void OnUsuarioIDChanged();
    #endregion
		
		public Activo()
		{
			this._Carrito = default(EntityRef<Carrito>);
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[Column(Storage="_CarritoID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CarritoID
		{
			get
			{
				return this._CarritoID;
			}
			set
			{
				if ((this._CarritoID != value))
				{
					if (this._Carrito.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCarritoIDChanging(value);
					this.SendPropertyChanging();
					this._CarritoID = value;
					this.SendPropertyChanged("CarritoID");
					this.OnCarritoIDChanged();
				}
			}
		}
		
		[Column(Storage="_UsuarioID", DbType="Int NOT NULL")]
		public int UsuarioID
		{
			get
			{
				return this._UsuarioID;
			}
			set
			{
				if ((this._UsuarioID != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUsuarioIDChanging(value);
					this.SendPropertyChanging();
					this._UsuarioID = value;
					this.SendPropertyChanged("UsuarioID");
					this.OnUsuarioIDChanged();
				}
			}
		}
		
		[Association(Name="Carrito_Activo", Storage="_Carrito", ThisKey="CarritoID", IsForeignKey=true)]
		public Carrito Carrito
		{
			get
			{
				return this._Carrito.Entity;
			}
			set
			{
				Carrito previousValue = this._Carrito.Entity;
				if (((previousValue != value) 
							|| (this._Carrito.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Carrito.Entity = null;
						previousValue.Activo = null;
					}
					this._Carrito.Entity = value;
					if ((value != null))
					{
						value.Activo = this;
						this._CarritoID = value.CarritoID;
					}
					else
					{
						this._CarritoID = default(int);
					}
					this.SendPropertyChanged("Carrito");
				}
			}
		}
		
		[Association(Name="Usuario_Activo", Storage="_Usuario", ThisKey="UsuarioID", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Activos.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Activos.Add(this);
						this._UsuarioID = value.UsuarioID;
					}
					else
					{
						this._UsuarioID = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.Vendido")]
	public partial class Vendido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CarritoID;
		
		private System.DateTime _Fecha;
		
		private double _Total;
		
		private int _UsuarioID;
		
		private int _MetodoDePagoID;
		
		private EntityRef<Carrito> _Carrito;
		
		private EntityRef<MetodoDePago> _MetodoDePago;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCarritoIDChanging(int value);
    partial void OnCarritoIDChanged();
    partial void OnFechaChanging(System.DateTime value);
    partial void OnFechaChanged();
    partial void OnTotalChanging(double value);
    partial void OnTotalChanged();
    partial void OnUsuarioIDChanging(int value);
    partial void OnUsuarioIDChanged();
    partial void OnMetodoDePagoIDChanging(int value);
    partial void OnMetodoDePagoIDChanged();
    #endregion
		
		public Vendido()
		{
			this._Carrito = default(EntityRef<Carrito>);
			this._MetodoDePago = default(EntityRef<MetodoDePago>);
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[Column(Storage="_CarritoID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CarritoID
		{
			get
			{
				return this._CarritoID;
			}
			set
			{
				if ((this._CarritoID != value))
				{
					if (this._Carrito.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCarritoIDChanging(value);
					this.SendPropertyChanging();
					this._CarritoID = value;
					this.SendPropertyChanged("CarritoID");
					this.OnCarritoIDChanged();
				}
			}
		}
		
		[Column(Storage="_Fecha", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[Column(Storage="_Total", DbType="Float NOT NULL")]
		public double Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this.OnTotalChanging(value);
					this.SendPropertyChanging();
					this._Total = value;
					this.SendPropertyChanged("Total");
					this.OnTotalChanged();
				}
			}
		}
		
		[Column(Storage="_UsuarioID", DbType="Int NOT NULL")]
		public int UsuarioID
		{
			get
			{
				return this._UsuarioID;
			}
			set
			{
				if ((this._UsuarioID != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUsuarioIDChanging(value);
					this.SendPropertyChanging();
					this._UsuarioID = value;
					this.SendPropertyChanged("UsuarioID");
					this.OnUsuarioIDChanged();
				}
			}
		}
		
		[Column(Storage="_MetodoDePagoID", DbType="Int NOT NULL")]
		public int MetodoDePagoID
		{
			get
			{
				return this._MetodoDePagoID;
			}
			set
			{
				if ((this._MetodoDePagoID != value))
				{
					if (this._MetodoDePago.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMetodoDePagoIDChanging(value);
					this.SendPropertyChanging();
					this._MetodoDePagoID = value;
					this.SendPropertyChanged("MetodoDePagoID");
					this.OnMetodoDePagoIDChanged();
				}
			}
		}
		
		[Association(Name="Carrito_Vendido", Storage="_Carrito", ThisKey="CarritoID", IsForeignKey=true)]
		public Carrito Carrito
		{
			get
			{
				return this._Carrito.Entity;
			}
			set
			{
				Carrito previousValue = this._Carrito.Entity;
				if (((previousValue != value) 
							|| (this._Carrito.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Carrito.Entity = null;
						previousValue.Vendido = null;
					}
					this._Carrito.Entity = value;
					if ((value != null))
					{
						value.Vendido = this;
						this._CarritoID = value.CarritoID;
					}
					else
					{
						this._CarritoID = default(int);
					}
					this.SendPropertyChanged("Carrito");
				}
			}
		}
		
		[Association(Name="MetodoDePago_Vendido", Storage="_MetodoDePago", ThisKey="MetodoDePagoID", IsForeignKey=true)]
		public MetodoDePago MetodoDePago
		{
			get
			{
				return this._MetodoDePago.Entity;
			}
			set
			{
				MetodoDePago previousValue = this._MetodoDePago.Entity;
				if (((previousValue != value) 
							|| (this._MetodoDePago.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MetodoDePago.Entity = null;
						previousValue.Vendidos.Remove(this);
					}
					this._MetodoDePago.Entity = value;
					if ((value != null))
					{
						value.Vendidos.Add(this);
						this._MetodoDePagoID = value.MetodoDePagoID;
					}
					else
					{
						this._MetodoDePagoID = default(int);
					}
					this.SendPropertyChanged("MetodoDePago");
				}
			}
		}
		
		[Association(Name="Usuario_Vendido", Storage="_Usuario", ThisKey="UsuarioID", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Vendidos.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Vendidos.Add(this);
						this._UsuarioID = value.UsuarioID;
					}
					else
					{
						this._UsuarioID = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.Carrito")]
	public partial class Carrito : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CarritoID;
		
		private EntityRef<Activo> _Activo;
		
		private EntityRef<Vendido> _Vendido;
		
		private EntitySet<Producto_Carrito> _Producto_Carritos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCarritoIDChanging(int value);
    partial void OnCarritoIDChanged();
    #endregion
		
		public Carrito()
		{
			this._Activo = default(EntityRef<Activo>);
			this._Vendido = default(EntityRef<Vendido>);
			this._Producto_Carritos = new EntitySet<Producto_Carrito>(new Action<Producto_Carrito>(this.attach_Producto_Carritos), new Action<Producto_Carrito>(this.detach_Producto_Carritos));
			OnCreated();
		}
		
		[Column(Storage="_CarritoID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CarritoID
		{
			get
			{
				return this._CarritoID;
			}
			set
			{
				if ((this._CarritoID != value))
				{
					this.OnCarritoIDChanging(value);
					this.SendPropertyChanging();
					this._CarritoID = value;
					this.SendPropertyChanged("CarritoID");
					this.OnCarritoIDChanged();
				}
			}
		}
		
		[Association(Name="Carrito_Activo", Storage="_Activo", ThisKey="CarritoID", IsUnique=true, IsForeignKey=false)]
		public Activo Activo
		{
			get
			{
				return this._Activo.Entity;
			}
			set
			{
				Activo previousValue = this._Activo.Entity;
				if (((previousValue != value) 
							|| (this._Activo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Activo.Entity = null;
						previousValue.Carrito = null;
					}
					this._Activo.Entity = value;
					if ((value != null))
					{
						value.Carrito = this;
					}
					this.SendPropertyChanged("Activo");
				}
			}
		}
		
		[Association(Name="Carrito_Vendido", Storage="_Vendido", ThisKey="CarritoID", IsUnique=true, IsForeignKey=false)]
		public Vendido Vendido
		{
			get
			{
				return this._Vendido.Entity;
			}
			set
			{
				Vendido previousValue = this._Vendido.Entity;
				if (((previousValue != value) 
							|| (this._Vendido.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Vendido.Entity = null;
						previousValue.Carrito = null;
					}
					this._Vendido.Entity = value;
					if ((value != null))
					{
						value.Carrito = this;
					}
					this.SendPropertyChanged("Vendido");
				}
			}
		}
		
		[Association(Name="Carrito_Producto_Carrito", Storage="_Producto_Carritos", OtherKey="CarritoID")]
		public EntitySet<Producto_Carrito> Producto_Carritos
		{
			get
			{
				return this._Producto_Carritos;
			}
			set
			{
				this._Producto_Carritos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Producto_Carritos(Producto_Carrito entity)
		{
			this.SendPropertyChanging();
			entity.Carrito = this;
		}
		
		private void detach_Producto_Carritos(Producto_Carrito entity)
		{
			this.SendPropertyChanging();
			entity.Carrito = null;
		}
	}
	
	[Table(Name="dbo.Categoria")]
	public partial class Categoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CategoriaID;
		
		private string _Nombre;
		
		private EntitySet<SubCategoria> _SubCategorias;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCategoriaIDChanging(int value);
    partial void OnCategoriaIDChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public Categoria()
		{
			this._SubCategorias = new EntitySet<SubCategoria>(new Action<SubCategoria>(this.attach_SubCategorias), new Action<SubCategoria>(this.detach_SubCategorias));
			OnCreated();
		}
		
		[Column(Storage="_CategoriaID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CategoriaID
		{
			get
			{
				return this._CategoriaID;
			}
			set
			{
				if ((this._CategoriaID != value))
				{
					this.OnCategoriaIDChanging(value);
					this.SendPropertyChanging();
					this._CategoriaID = value;
					this.SendPropertyChanged("CategoriaID");
					this.OnCategoriaIDChanged();
				}
			}
		}
		
		[Column(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[Association(Name="Categoria_SubCategoria", Storage="_SubCategorias", OtherKey="CategoriaID")]
		public EntitySet<SubCategoria> SubCategorias
		{
			get
			{
				return this._SubCategorias;
			}
			set
			{
				this._SubCategorias.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SubCategorias(SubCategoria entity)
		{
			this.SendPropertyChanging();
			entity.Categoria = this;
		}
		
		private void detach_SubCategorias(SubCategoria entity)
		{
			this.SendPropertyChanging();
			entity.Categoria = null;
		}
	}
	
	[Table(Name="dbo.MetodoDePago")]
	public partial class MetodoDePago : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MetodoDePagoID;
		
		private double _Numero;
		
		private EntitySet<Vendido> _Vendidos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMetodoDePagoIDChanging(int value);
    partial void OnMetodoDePagoIDChanged();
    partial void OnNumeroChanging(double value);
    partial void OnNumeroChanged();
    #endregion
		
		public MetodoDePago()
		{
			this._Vendidos = new EntitySet<Vendido>(new Action<Vendido>(this.attach_Vendidos), new Action<Vendido>(this.detach_Vendidos));
			OnCreated();
		}
		
		[Column(Storage="_MetodoDePagoID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, IsDiscriminator=true)]
		public int MetodoDePagoID
		{
			get
			{
				return this._MetodoDePagoID;
			}
			set
			{
				if ((this._MetodoDePagoID != value))
				{
					this.OnMetodoDePagoIDChanging(value);
					this.SendPropertyChanging();
					this._MetodoDePagoID = value;
					this.SendPropertyChanged("MetodoDePagoID");
					this.OnMetodoDePagoIDChanged();
				}
			}
		}
		
		[Column(Storage="_Numero", DbType="Float NOT NULL")]
		public double Numero
		{
			get
			{
				return this._Numero;
			}
			set
			{
				if ((this._Numero != value))
				{
					this.OnNumeroChanging(value);
					this.SendPropertyChanging();
					this._Numero = value;
					this.SendPropertyChanged("Numero");
					this.OnNumeroChanged();
				}
			}
		}
		
		[Association(Name="MetodoDePago_Vendido", Storage="_Vendidos", OtherKey="MetodoDePagoID")]
		public EntitySet<Vendido> Vendidos
		{
			get
			{
				return this._Vendidos;
			}
			set
			{
				this._Vendidos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Vendidos(Vendido entity)
		{
			this.SendPropertyChanging();
			entity.MetodoDePago = this;
		}
		
		private void detach_Vendidos(Vendido entity)
		{
			this.SendPropertyChanging();
			entity.MetodoDePago = null;
		}
	}
	
	public partial class PayPal : MetodoDePago
	{
		
		private int _MetodoDePagoID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMetodoDePagoIDChanging(int value);
    partial void OnMetodoDePagoIDChanged();
    #endregion
		
		public PayPal()
		{
			OnCreated();
		}
		
		[Column(Storage="_MetodoDePagoID", DbType="Int NOT NULL")]
		public int MetodoDePagoID
		{
			get
			{
				return this._MetodoDePagoID;
			}
			set
			{
				if ((this._MetodoDePagoID != value))
				{
					this.OnMetodoDePagoIDChanging(value);
					this.SendPropertyChanging();
					this._MetodoDePagoID = value;
					this.SendPropertyChanged("MetodoDePagoID");
					this.OnMetodoDePagoIDChanged();
				}
			}
		}
	}
	
	public partial class Tarjeta : MetodoDePago
	{
		
		private int _MetodoDePagoID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMetodoDePagoIDChanging(int value);
    partial void OnMetodoDePagoIDChanged();
    #endregion
		
		public Tarjeta()
		{
			OnCreated();
		}
		
		[Column(Storage="_MetodoDePagoID", DbType="Int NOT NULL")]
		public int MetodoDePagoID
		{
			get
			{
				return this._MetodoDePagoID;
			}
			set
			{
				if ((this._MetodoDePagoID != value))
				{
					this.OnMetodoDePagoIDChanging(value);
					this.SendPropertyChanging();
					this._MetodoDePagoID = value;
					this.SendPropertyChanged("MetodoDePagoID");
					this.OnMetodoDePagoIDChanged();
				}
			}
		}
	}
	
	[Table(Name="dbo.Producto")]
	public partial class Producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProductoID;
		
		private EntitySet<Producto_Carrito> _Producto_Carritos;
		
		private EntitySet<Producto_Tag> _Producto_Tags;
		
		private EntitySet<Producto_Usuario> _Producto_Usuarios;
		
		private EntitySet<Valor> _Valors;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProductoIDChanging(int value);
    partial void OnProductoIDChanged();
    #endregion
		
		public Producto()
		{
			this._Producto_Carritos = new EntitySet<Producto_Carrito>(new Action<Producto_Carrito>(this.attach_Producto_Carritos), new Action<Producto_Carrito>(this.detach_Producto_Carritos));
			this._Producto_Tags = new EntitySet<Producto_Tag>(new Action<Producto_Tag>(this.attach_Producto_Tags), new Action<Producto_Tag>(this.detach_Producto_Tags));
			this._Producto_Usuarios = new EntitySet<Producto_Usuario>(new Action<Producto_Usuario>(this.attach_Producto_Usuarios), new Action<Producto_Usuario>(this.detach_Producto_Usuarios));
			this._Valors = new EntitySet<Valor>(new Action<Valor>(this.attach_Valors), new Action<Valor>(this.detach_Valors));
			OnCreated();
		}
		
		[Column(Storage="_ProductoID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProductoID
		{
			get
			{
				return this._ProductoID;
			}
			set
			{
				if ((this._ProductoID != value))
				{
					this.OnProductoIDChanging(value);
					this.SendPropertyChanging();
					this._ProductoID = value;
					this.SendPropertyChanged("ProductoID");
					this.OnProductoIDChanged();
				}
			}
		}
		
		[Association(Name="Producto_Producto_Carrito", Storage="_Producto_Carritos", OtherKey="ProductoID")]
		public EntitySet<Producto_Carrito> Producto_Carritos
		{
			get
			{
				return this._Producto_Carritos;
			}
			set
			{
				this._Producto_Carritos.Assign(value);
			}
		}
		
		[Association(Name="Producto_Producto_Tag", Storage="_Producto_Tags", OtherKey="ProductoID")]
		public EntitySet<Producto_Tag> Producto_Tags
		{
			get
			{
				return this._Producto_Tags;
			}
			set
			{
				this._Producto_Tags.Assign(value);
			}
		}
		
		[Association(Name="Producto_Producto_Usuario", Storage="_Producto_Usuarios", OtherKey="ProductoID")]
		public EntitySet<Producto_Usuario> Producto_Usuarios
		{
			get
			{
				return this._Producto_Usuarios;
			}
			set
			{
				this._Producto_Usuarios.Assign(value);
			}
		}
		
		[Association(Name="Producto_Valor", Storage="_Valors", OtherKey="ProductoID")]
		public EntitySet<Valor> Valors
		{
			get
			{
				return this._Valors;
			}
			set
			{
				this._Valors.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Producto_Carritos(Producto_Carrito entity)
		{
			this.SendPropertyChanging();
			entity.Producto = this;
		}
		
		private void detach_Producto_Carritos(Producto_Carrito entity)
		{
			this.SendPropertyChanging();
			entity.Producto = null;
		}
		
		private void attach_Producto_Tags(Producto_Tag entity)
		{
			this.SendPropertyChanging();
			entity.Producto = this;
		}
		
		private void detach_Producto_Tags(Producto_Tag entity)
		{
			this.SendPropertyChanging();
			entity.Producto = null;
		}
		
		private void attach_Producto_Usuarios(Producto_Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Producto = this;
		}
		
		private void detach_Producto_Usuarios(Producto_Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Producto = null;
		}
		
		private void attach_Valors(Valor entity)
		{
			this.SendPropertyChanging();
			entity.Producto = this;
		}
		
		private void detach_Valors(Valor entity)
		{
			this.SendPropertyChanging();
			entity.Producto = null;
		}
	}
	
	[Table(Name="dbo.Producto_Carrito")]
	public partial class Producto_Carrito : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProductoID;
		
		private int _CarritoID;
		
		private char _EstaEnCarrito;
		
		private EntityRef<Carrito> _Carrito;
		
		private EntityRef<Producto> _Producto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProductoIDChanging(int value);
    partial void OnProductoIDChanged();
    partial void OnCarritoIDChanging(int value);
    partial void OnCarritoIDChanged();
    partial void OnEstaEnCarritoChanging(char value);
    partial void OnEstaEnCarritoChanged();
    #endregion
		
		public Producto_Carrito()
		{
			this._Carrito = default(EntityRef<Carrito>);
			this._Producto = default(EntityRef<Producto>);
			OnCreated();
		}
		
		[Column(Storage="_ProductoID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ProductoID
		{
			get
			{
				return this._ProductoID;
			}
			set
			{
				if ((this._ProductoID != value))
				{
					if (this._Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProductoIDChanging(value);
					this.SendPropertyChanging();
					this._ProductoID = value;
					this.SendPropertyChanged("ProductoID");
					this.OnProductoIDChanged();
				}
			}
		}
		
		[Column(Storage="_CarritoID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CarritoID
		{
			get
			{
				return this._CarritoID;
			}
			set
			{
				if ((this._CarritoID != value))
				{
					if (this._Carrito.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCarritoIDChanging(value);
					this.SendPropertyChanging();
					this._CarritoID = value;
					this.SendPropertyChanged("CarritoID");
					this.OnCarritoIDChanged();
				}
			}
		}
		
		[Column(Storage="_EstaEnCarrito", DbType="VarChar(1) NOT NULL")]
		public char EstaEnCarrito
		{
			get
			{
				return this._EstaEnCarrito;
			}
			set
			{
				if ((this._EstaEnCarrito != value))
				{
					this.OnEstaEnCarritoChanging(value);
					this.SendPropertyChanging();
					this._EstaEnCarrito = value;
					this.SendPropertyChanged("EstaEnCarrito");
					this.OnEstaEnCarritoChanged();
				}
			}
		}
		
		[Association(Name="Carrito_Producto_Carrito", Storage="_Carrito", ThisKey="CarritoID", IsForeignKey=true)]
		public Carrito Carrito
		{
			get
			{
				return this._Carrito.Entity;
			}
			set
			{
				Carrito previousValue = this._Carrito.Entity;
				if (((previousValue != value) 
							|| (this._Carrito.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Carrito.Entity = null;
						previousValue.Producto_Carritos.Remove(this);
					}
					this._Carrito.Entity = value;
					if ((value != null))
					{
						value.Producto_Carritos.Add(this);
						this._CarritoID = value.CarritoID;
					}
					else
					{
						this._CarritoID = default(int);
					}
					this.SendPropertyChanged("Carrito");
				}
			}
		}
		
		[Association(Name="Producto_Producto_Carrito", Storage="_Producto", ThisKey="ProductoID", IsForeignKey=true)]
		public Producto Producto
		{
			get
			{
				return this._Producto.Entity;
			}
			set
			{
				Producto previousValue = this._Producto.Entity;
				if (((previousValue != value) 
							|| (this._Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Producto.Entity = null;
						previousValue.Producto_Carritos.Remove(this);
					}
					this._Producto.Entity = value;
					if ((value != null))
					{
						value.Producto_Carritos.Add(this);
						this._ProductoID = value.ProductoID;
					}
					else
					{
						this._ProductoID = default(int);
					}
					this.SendPropertyChanged("Producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.Producto_Tag")]
	public partial class Producto_Tag : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProductoID;
		
		private int _TagID;
		
		private EntityRef<Producto> _Producto;
		
		private EntityRef<Tag> _Tag;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProductoIDChanging(int value);
    partial void OnProductoIDChanged();
    partial void OnTagIDChanging(int value);
    partial void OnTagIDChanged();
    #endregion
		
		public Producto_Tag()
		{
			this._Producto = default(EntityRef<Producto>);
			this._Tag = default(EntityRef<Tag>);
			OnCreated();
		}
		
		[Column(Storage="_ProductoID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ProductoID
		{
			get
			{
				return this._ProductoID;
			}
			set
			{
				if ((this._ProductoID != value))
				{
					if (this._Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProductoIDChanging(value);
					this.SendPropertyChanging();
					this._ProductoID = value;
					this.SendPropertyChanged("ProductoID");
					this.OnProductoIDChanged();
				}
			}
		}
		
		[Column(Storage="_TagID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TagID
		{
			get
			{
				return this._TagID;
			}
			set
			{
				if ((this._TagID != value))
				{
					if (this._Tag.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTagIDChanging(value);
					this.SendPropertyChanging();
					this._TagID = value;
					this.SendPropertyChanged("TagID");
					this.OnTagIDChanged();
				}
			}
		}
		
		[Association(Name="Producto_Producto_Tag", Storage="_Producto", ThisKey="ProductoID", IsForeignKey=true)]
		public Producto Producto
		{
			get
			{
				return this._Producto.Entity;
			}
			set
			{
				Producto previousValue = this._Producto.Entity;
				if (((previousValue != value) 
							|| (this._Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Producto.Entity = null;
						previousValue.Producto_Tags.Remove(this);
					}
					this._Producto.Entity = value;
					if ((value != null))
					{
						value.Producto_Tags.Add(this);
						this._ProductoID = value.ProductoID;
					}
					else
					{
						this._ProductoID = default(int);
					}
					this.SendPropertyChanged("Producto");
				}
			}
		}
		
		[Association(Name="Tag_Producto_Tag", Storage="_Tag", ThisKey="TagID", IsForeignKey=true)]
		public Tag Tag
		{
			get
			{
				return this._Tag.Entity;
			}
			set
			{
				Tag previousValue = this._Tag.Entity;
				if (((previousValue != value) 
							|| (this._Tag.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tag.Entity = null;
						previousValue.Producto_Tags.Remove(this);
					}
					this._Tag.Entity = value;
					if ((value != null))
					{
						value.Producto_Tags.Add(this);
						this._TagID = value.TagID;
					}
					else
					{
						this._TagID = default(int);
					}
					this.SendPropertyChanged("Tag");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.Producto_Usuario")]
	public partial class Producto_Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProductoID;
		
		private int _UsuarioID;
		
		private System.Nullable<double> _Puntaje;
		
		private string _Comentario;
		
		private EntityRef<Producto> _Producto;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProductoIDChanging(int value);
    partial void OnProductoIDChanged();
    partial void OnUsuarioIDChanging(int value);
    partial void OnUsuarioIDChanged();
    partial void OnPuntajeChanging(System.Nullable<double> value);
    partial void OnPuntajeChanged();
    partial void OnComentarioChanging(string value);
    partial void OnComentarioChanged();
    #endregion
		
		public Producto_Usuario()
		{
			this._Producto = default(EntityRef<Producto>);
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[Column(Storage="_ProductoID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ProductoID
		{
			get
			{
				return this._ProductoID;
			}
			set
			{
				if ((this._ProductoID != value))
				{
					if (this._Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProductoIDChanging(value);
					this.SendPropertyChanging();
					this._ProductoID = value;
					this.SendPropertyChanged("ProductoID");
					this.OnProductoIDChanged();
				}
			}
		}
		
		[Column(Storage="_UsuarioID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int UsuarioID
		{
			get
			{
				return this._UsuarioID;
			}
			set
			{
				if ((this._UsuarioID != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUsuarioIDChanging(value);
					this.SendPropertyChanging();
					this._UsuarioID = value;
					this.SendPropertyChanged("UsuarioID");
					this.OnUsuarioIDChanged();
				}
			}
		}
		
		[Column(Storage="_Puntaje", DbType="Float")]
		public System.Nullable<double> Puntaje
		{
			get
			{
				return this._Puntaje;
			}
			set
			{
				if ((this._Puntaje != value))
				{
					this.OnPuntajeChanging(value);
					this.SendPropertyChanging();
					this._Puntaje = value;
					this.SendPropertyChanged("Puntaje");
					this.OnPuntajeChanged();
				}
			}
		}
		
		[Column(Storage="_Comentario", DbType="VarChar(150)")]
		public string Comentario
		{
			get
			{
				return this._Comentario;
			}
			set
			{
				if ((this._Comentario != value))
				{
					this.OnComentarioChanging(value);
					this.SendPropertyChanging();
					this._Comentario = value;
					this.SendPropertyChanged("Comentario");
					this.OnComentarioChanged();
				}
			}
		}
		
		[Association(Name="Producto_Producto_Usuario", Storage="_Producto", ThisKey="ProductoID", IsForeignKey=true)]
		public Producto Producto
		{
			get
			{
				return this._Producto.Entity;
			}
			set
			{
				Producto previousValue = this._Producto.Entity;
				if (((previousValue != value) 
							|| (this._Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Producto.Entity = null;
						previousValue.Producto_Usuarios.Remove(this);
					}
					this._Producto.Entity = value;
					if ((value != null))
					{
						value.Producto_Usuarios.Add(this);
						this._ProductoID = value.ProductoID;
					}
					else
					{
						this._ProductoID = default(int);
					}
					this.SendPropertyChanged("Producto");
				}
			}
		}
		
		[Association(Name="Usuario_Producto_Usuario", Storage="_Usuario", ThisKey="UsuarioID", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Producto_Usuarios.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Producto_Usuarios.Add(this);
						this._UsuarioID = value.UsuarioID;
					}
					else
					{
						this._UsuarioID = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.Propiedad")]
	public partial class Propiedad : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PropiedadID;
		
		private string _Nombre;
		
		private EntitySet<SubCategoria_Propiedad> _SubCategoria_Propiedads;
		
		private EntitySet<Valor> _Valors;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPropiedadIDChanging(int value);
    partial void OnPropiedadIDChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public Propiedad()
		{
			this._SubCategoria_Propiedads = new EntitySet<SubCategoria_Propiedad>(new Action<SubCategoria_Propiedad>(this.attach_SubCategoria_Propiedads), new Action<SubCategoria_Propiedad>(this.detach_SubCategoria_Propiedads));
			this._Valors = new EntitySet<Valor>(new Action<Valor>(this.attach_Valors), new Action<Valor>(this.detach_Valors));
			OnCreated();
		}
		
		[Column(Storage="_PropiedadID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PropiedadID
		{
			get
			{
				return this._PropiedadID;
			}
			set
			{
				if ((this._PropiedadID != value))
				{
					this.OnPropiedadIDChanging(value);
					this.SendPropertyChanging();
					this._PropiedadID = value;
					this.SendPropertyChanged("PropiedadID");
					this.OnPropiedadIDChanged();
				}
			}
		}
		
		[Column(Storage="_Nombre", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[Association(Name="Propiedad_SubCategoria_Propiedad", Storage="_SubCategoria_Propiedads", OtherKey="PropiedadID")]
		public EntitySet<SubCategoria_Propiedad> SubCategoria_Propiedads
		{
			get
			{
				return this._SubCategoria_Propiedads;
			}
			set
			{
				this._SubCategoria_Propiedads.Assign(value);
			}
		}
		
		[Association(Name="Propiedad_Valor", Storage="_Valors", OtherKey="PropiedadID")]
		public EntitySet<Valor> Valors
		{
			get
			{
				return this._Valors;
			}
			set
			{
				this._Valors.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SubCategoria_Propiedads(SubCategoria_Propiedad entity)
		{
			this.SendPropertyChanging();
			entity.Propiedad = this;
		}
		
		private void detach_SubCategoria_Propiedads(SubCategoria_Propiedad entity)
		{
			this.SendPropertyChanging();
			entity.Propiedad = null;
		}
		
		private void attach_Valors(Valor entity)
		{
			this.SendPropertyChanging();
			entity.Propiedad = this;
		}
		
		private void detach_Valors(Valor entity)
		{
			this.SendPropertyChanging();
			entity.Propiedad = null;
		}
	}
	
	[Table(Name="dbo.SubCategoria")]
	public partial class SubCategoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SubCategoriaID;
		
		private string _Nombre;
		
		private int _CategoriaID;
		
		private EntitySet<SubCategoria_Propiedad> _SubCategoria_Propiedads;
		
		private EntityRef<Categoria> _Categoria;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSubCategoriaIDChanging(int value);
    partial void OnSubCategoriaIDChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnCategoriaIDChanging(int value);
    partial void OnCategoriaIDChanged();
    #endregion
		
		public SubCategoria()
		{
			this._SubCategoria_Propiedads = new EntitySet<SubCategoria_Propiedad>(new Action<SubCategoria_Propiedad>(this.attach_SubCategoria_Propiedads), new Action<SubCategoria_Propiedad>(this.detach_SubCategoria_Propiedads));
			this._Categoria = default(EntityRef<Categoria>);
			OnCreated();
		}
		
		[Column(Storage="_SubCategoriaID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SubCategoriaID
		{
			get
			{
				return this._SubCategoriaID;
			}
			set
			{
				if ((this._SubCategoriaID != value))
				{
					this.OnSubCategoriaIDChanging(value);
					this.SendPropertyChanging();
					this._SubCategoriaID = value;
					this.SendPropertyChanged("SubCategoriaID");
					this.OnSubCategoriaIDChanged();
				}
			}
		}
		
		[Column(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[Column(Storage="_CategoriaID", DbType="Int NOT NULL")]
		public int CategoriaID
		{
			get
			{
				return this._CategoriaID;
			}
			set
			{
				if ((this._CategoriaID != value))
				{
					if (this._Categoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCategoriaIDChanging(value);
					this.SendPropertyChanging();
					this._CategoriaID = value;
					this.SendPropertyChanged("CategoriaID");
					this.OnCategoriaIDChanged();
				}
			}
		}
		
		[Association(Name="SubCategoria_SubCategoria_Propiedad", Storage="_SubCategoria_Propiedads", OtherKey="SubCategoriaID")]
		public EntitySet<SubCategoria_Propiedad> SubCategoria_Propiedads
		{
			get
			{
				return this._SubCategoria_Propiedads;
			}
			set
			{
				this._SubCategoria_Propiedads.Assign(value);
			}
		}
		
		[Association(Name="Categoria_SubCategoria", Storage="_Categoria", ThisKey="CategoriaID", IsForeignKey=true)]
		public Categoria Categoria
		{
			get
			{
				return this._Categoria.Entity;
			}
			set
			{
				Categoria previousValue = this._Categoria.Entity;
				if (((previousValue != value) 
							|| (this._Categoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Categoria.Entity = null;
						previousValue.SubCategorias.Remove(this);
					}
					this._Categoria.Entity = value;
					if ((value != null))
					{
						value.SubCategorias.Add(this);
						this._CategoriaID = value.CategoriaID;
					}
					else
					{
						this._CategoriaID = default(int);
					}
					this.SendPropertyChanged("Categoria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SubCategoria_Propiedads(SubCategoria_Propiedad entity)
		{
			this.SendPropertyChanging();
			entity.SubCategoria = this;
		}
		
		private void detach_SubCategoria_Propiedads(SubCategoria_Propiedad entity)
		{
			this.SendPropertyChanging();
			entity.SubCategoria = null;
		}
    }
	
	[Table(Name="dbo.SubCategoria_Propiedad")]
	public partial class SubCategoria_Propiedad : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SubCategoriaID;
		
		private int _PropiedadID;
		
		private char _IsIdentificador;
		
		private EntityRef<Propiedad> _Propiedad;
		
		private EntityRef<SubCategoria> _SubCategoria;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSubCategoriaIDChanging(int value);
    partial void OnSubCategoriaIDChanged();
    partial void OnPropiedadIDChanging(int value);
    partial void OnPropiedadIDChanged();
    partial void OnIsIdentificadorChanging(char value);
    partial void OnIsIdentificadorChanged();
    #endregion
		
		public SubCategoria_Propiedad()
		{
			this._Propiedad = default(EntityRef<Propiedad>);
			this._SubCategoria = default(EntityRef<SubCategoria>);
			OnCreated();
		}
		
		[Column(Storage="_SubCategoriaID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SubCategoriaID
		{
			get
			{
				return this._SubCategoriaID;
			}
			set
			{
				if ((this._SubCategoriaID != value))
				{
					if (this._SubCategoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSubCategoriaIDChanging(value);
					this.SendPropertyChanging();
					this._SubCategoriaID = value;
					this.SendPropertyChanged("SubCategoriaID");
					this.OnSubCategoriaIDChanged();
				}
			}
		}
		
		[Column(Storage="_PropiedadID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PropiedadID
		{
			get
			{
				return this._PropiedadID;
			}
			set
			{
				if ((this._PropiedadID != value))
				{
					if (this._Propiedad.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPropiedadIDChanging(value);
					this.SendPropertyChanging();
					this._PropiedadID = value;
					this.SendPropertyChanged("PropiedadID");
					this.OnPropiedadIDChanged();
				}
			}
		}
		
		[Column(Storage="_IsIdentificador", DbType="VarChar(1) NOT NULL")]
		public char IsIdentificador
		{
			get
			{
				return this._IsIdentificador;
			}
			set
			{
				if ((this._IsIdentificador != value))
				{
					this.OnIsIdentificadorChanging(value);
					this.SendPropertyChanging();
					this._IsIdentificador = value;
					this.SendPropertyChanged("IsIdentificador");
					this.OnIsIdentificadorChanged();
				}
			}
		}
		
		[Association(Name="Propiedad_SubCategoria_Propiedad", Storage="_Propiedad", ThisKey="PropiedadID", IsForeignKey=true)]
		public Propiedad Propiedad
		{
			get
			{
				return this._Propiedad.Entity;
			}
			set
			{
				Propiedad previousValue = this._Propiedad.Entity;
				if (((previousValue != value) 
							|| (this._Propiedad.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Propiedad.Entity = null;
						previousValue.SubCategoria_Propiedads.Remove(this);
					}
					this._Propiedad.Entity = value;
					if ((value != null))
					{
						value.SubCategoria_Propiedads.Add(this);
						this._PropiedadID = value.PropiedadID;
					}
					else
					{
						this._PropiedadID = default(int);
					}
					this.SendPropertyChanged("Propiedad");
				}
			}
		}
		
		[Association(Name="SubCategoria_SubCategoria_Propiedad", Storage="_SubCategoria", ThisKey="SubCategoriaID", IsForeignKey=true)]
		public SubCategoria SubCategoria
		{
			get
			{
				return this._SubCategoria.Entity;
			}
			set
			{
				SubCategoria previousValue = this._SubCategoria.Entity;
				if (((previousValue != value) 
							|| (this._SubCategoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SubCategoria.Entity = null;
						previousValue.SubCategoria_Propiedads.Remove(this);
					}
					this._SubCategoria.Entity = value;
					if ((value != null))
					{
						value.SubCategoria_Propiedads.Add(this);
						this._SubCategoriaID = value.SubCategoriaID;
					}
					else
					{
						this._SubCategoriaID = default(int);
					}
					this.SendPropertyChanged("SubCategoria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.Sucursal")]
	public partial class Sucursal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SucursalID;
		
		private string _Nombre;
		
		private string _Direccion;
		
		private double _Latitud;
		
		private double _Longitud;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSucursalIDChanging(int value);
    partial void OnSucursalIDChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnLatitudChanging(double value);
    partial void OnLatitudChanged();
    partial void OnLongitudChanging(double value);
    partial void OnLongitudChanged();
    #endregion
		
		public Sucursal()
		{
			OnCreated();
		}
		
		[Column(Storage="_SucursalID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SucursalID
		{
			get
			{
				return this._SucursalID;
			}
			set
			{
				if ((this._SucursalID != value))
				{
					this.OnSucursalIDChanging(value);
					this.SendPropertyChanging();
					this._SucursalID = value;
					this.SendPropertyChanged("SucursalID");
					this.OnSucursalIDChanged();
				}
			}
		}
		
		[Column(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[Column(Storage="_Direccion", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[Column(Storage="_Latitud", DbType="Float NOT NULL")]
		public double Latitud
		{
			get
			{
				return this._Latitud;
			}
			set
			{
				if ((this._Latitud != value))
				{
					this.OnLatitudChanging(value);
					this.SendPropertyChanging();
					this._Latitud = value;
					this.SendPropertyChanged("Latitud");
					this.OnLatitudChanged();
				}
			}
		}
		
		[Column(Storage="_Longitud", DbType="Float NOT NULL")]
		public double Longitud
		{
			get
			{
				return this._Longitud;
			}
			set
			{
				if ((this._Longitud != value))
				{
					this.OnLongitudChanging(value);
					this.SendPropertyChanging();
					this._Longitud = value;
					this.SendPropertyChanged("Longitud");
					this.OnLongitudChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.Tag")]
	public partial class Tag : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TagID;
		
		private string _Nombre;
		
		private System.Nullable<int> _CantAp;
		
		private EntitySet<Producto_Tag> _Producto_Tags;
		
		private EntitySet<Usuario_Tag> _Usuario_Tags;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTagIDChanging(int value);
    partial void OnTagIDChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnCantApChanging(System.Nullable<int> value);
    partial void OnCantApChanged();
    #endregion
		
		public Tag()
		{
			this._Producto_Tags = new EntitySet<Producto_Tag>(new Action<Producto_Tag>(this.attach_Producto_Tags), new Action<Producto_Tag>(this.detach_Producto_Tags));
			this._Usuario_Tags = new EntitySet<Usuario_Tag>(new Action<Usuario_Tag>(this.attach_Usuario_Tags), new Action<Usuario_Tag>(this.detach_Usuario_Tags));
			OnCreated();
		}
		
		[Column(Storage="_TagID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TagID
		{
			get
			{
				return this._TagID;
			}
			set
			{
				if ((this._TagID != value))
				{
					this.OnTagIDChanging(value);
					this.SendPropertyChanging();
					this._TagID = value;
					this.SendPropertyChanged("TagID");
					this.OnTagIDChanged();
				}
			}
		}
		
		[Column(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[Column(Storage="_CantAp", DbType="Int")]
		public System.Nullable<int> CantAp
		{
			get
			{
				return this._CantAp;
			}
			set
			{
				if ((this._CantAp != value))
				{
					this.OnCantApChanging(value);
					this.SendPropertyChanging();
					this._CantAp = value;
					this.SendPropertyChanged("CantAp");
					this.OnCantApChanged();
				}
			}
		}
		
		[Association(Name="Tag_Producto_Tag", Storage="_Producto_Tags", OtherKey="TagID")]
		public EntitySet<Producto_Tag> Producto_Tags
		{
			get
			{
				return this._Producto_Tags;
			}
			set
			{
				this._Producto_Tags.Assign(value);
			}
		}
		
		[Association(Name="Tag_Usuario_Tag", Storage="_Usuario_Tags", OtherKey="TagID")]
		public EntitySet<Usuario_Tag> Usuario_Tags
		{
			get
			{
				return this._Usuario_Tags;
			}
			set
			{
				this._Usuario_Tags.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Producto_Tags(Producto_Tag entity)
		{
			this.SendPropertyChanging();
			entity.Tag = this;
		}
		
		private void detach_Producto_Tags(Producto_Tag entity)
		{
			this.SendPropertyChanging();
			entity.Tag = null;
		}
		
		private void attach_Usuario_Tags(Usuario_Tag entity)
		{
			this.SendPropertyChanging();
			entity.Tag = this;
		}
		
		private void detach_Usuario_Tags(Usuario_Tag entity)
		{
			this.SendPropertyChanging();
			entity.Tag = null;
		}
	}
	
	[Table(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UsuarioID;
		
		private string _Nombre;
		
		private string _Password;
		
		private EntitySet<Activo> _Activos;
		
		private EntitySet<Vendido> _Vendidos;
		
		private EntitySet<Producto_Usuario> _Producto_Usuarios;
		
		private EntitySet<Usuario_Tag> _Usuario_Tags;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsuarioIDChanging(int value);
    partial void OnUsuarioIDChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    #endregion
		
		public Usuario()
		{
			this._Activos = new EntitySet<Activo>(new Action<Activo>(this.attach_Activos), new Action<Activo>(this.detach_Activos));
			this._Vendidos = new EntitySet<Vendido>(new Action<Vendido>(this.attach_Vendidos), new Action<Vendido>(this.detach_Vendidos));
			this._Producto_Usuarios = new EntitySet<Producto_Usuario>(new Action<Producto_Usuario>(this.attach_Producto_Usuarios), new Action<Producto_Usuario>(this.detach_Producto_Usuarios));
			this._Usuario_Tags = new EntitySet<Usuario_Tag>(new Action<Usuario_Tag>(this.attach_Usuario_Tags), new Action<Usuario_Tag>(this.detach_Usuario_Tags));
			OnCreated();
		}
		
		[Column(Storage="_UsuarioID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UsuarioID
		{
			get
			{
				return this._UsuarioID;
			}
			set
			{
				if ((this._UsuarioID != value))
				{
					this.OnUsuarioIDChanging(value);
					this.SendPropertyChanging();
					this._UsuarioID = value;
					this.SendPropertyChanged("UsuarioID");
					this.OnUsuarioIDChanged();
				}
			}
		}
		
		[Column(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[Column(Storage="_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[Association(Name="Usuario_Activo", Storage="_Activos", OtherKey="UsuarioID")]
		public EntitySet<Activo> Activos
		{
			get
			{
				return this._Activos;
			}
			set
			{
				this._Activos.Assign(value);
			}
		}
		
		[Association(Name="Usuario_Vendido", Storage="_Vendidos", OtherKey="UsuarioID")]
		public EntitySet<Vendido> Vendidos
		{
			get
			{
				return this._Vendidos;
			}
			set
			{
				this._Vendidos.Assign(value);
			}
		}
		
		[Association(Name="Usuario_Producto_Usuario", Storage="_Producto_Usuarios", OtherKey="UsuarioID")]
		public EntitySet<Producto_Usuario> Producto_Usuarios
		{
			get
			{
				return this._Producto_Usuarios;
			}
			set
			{
				this._Producto_Usuarios.Assign(value);
			}
		}
		
		[Association(Name="Usuario_Usuario_Tag", Storage="_Usuario_Tags", OtherKey="UsuarioID")]
		public EntitySet<Usuario_Tag> Usuario_Tags
		{
			get
			{
				return this._Usuario_Tags;
			}
			set
			{
				this._Usuario_Tags.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Activos(Activo entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Activos(Activo entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
		
		private void attach_Vendidos(Vendido entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Vendidos(Vendido entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
		
		private void attach_Producto_Usuarios(Producto_Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Producto_Usuarios(Producto_Usuario entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
		
		private void attach_Usuario_Tags(Usuario_Tag entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Usuario_Tags(Usuario_Tag entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
	}
	
	[Table(Name="dbo.Usuario_Tag")]
	public partial class Usuario_Tag : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UsuarioID;
		
		private int _TagID;
		
		private EntityRef<Tag> _Tag;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsuarioIDChanging(int value);
    partial void OnUsuarioIDChanged();
    partial void OnTagIDChanging(int value);
    partial void OnTagIDChanged();
    #endregion
		
		public Usuario_Tag()
		{
			this._Tag = default(EntityRef<Tag>);
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[Column(Storage="_UsuarioID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int UsuarioID
		{
			get
			{
				return this._UsuarioID;
			}
			set
			{
				if ((this._UsuarioID != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUsuarioIDChanging(value);
					this.SendPropertyChanging();
					this._UsuarioID = value;
					this.SendPropertyChanged("UsuarioID");
					this.OnUsuarioIDChanged();
				}
			}
		}
		
		[Column(Storage="_TagID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TagID
		{
			get
			{
				return this._TagID;
			}
			set
			{
				if ((this._TagID != value))
				{
					if (this._Tag.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTagIDChanging(value);
					this.SendPropertyChanging();
					this._TagID = value;
					this.SendPropertyChanged("TagID");
					this.OnTagIDChanged();
				}
			}
		}
		
		[Association(Name="Tag_Usuario_Tag", Storage="_Tag", ThisKey="TagID", IsForeignKey=true)]
		public Tag Tag
		{
			get
			{
				return this._Tag.Entity;
			}
			set
			{
				Tag previousValue = this._Tag.Entity;
				if (((previousValue != value) 
							|| (this._Tag.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tag.Entity = null;
						previousValue.Usuario_Tags.Remove(this);
					}
					this._Tag.Entity = value;
					if ((value != null))
					{
						value.Usuario_Tags.Add(this);
						this._TagID = value.TagID;
					}
					else
					{
						this._TagID = default(int);
					}
					this.SendPropertyChanged("Tag");
				}
			}
		}
		
		[Association(Name="Usuario_Usuario_Tag", Storage="_Usuario", ThisKey="UsuarioID", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Usuario_Tags.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Usuario_Tags.Add(this);
						this._UsuarioID = value.UsuarioID;
					}
					else
					{
						this._UsuarioID = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.Valor")]
	public partial class Valor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProductoID;
		
		private int _PropiedadID;
		
		private string _Valor1;
		
		private EntityRef<Propiedad> _Propiedad;
		
		private EntityRef<Producto> _Producto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProductoIDChanging(int value);
    partial void OnProductoIDChanged();
    partial void OnPropiedadIDChanging(int value);
    partial void OnPropiedadIDChanged();
    partial void OnValor1Changing(string value);
    partial void OnValor1Changed();
    #endregion
		
		public Valor()
		{
			this._Propiedad = default(EntityRef<Propiedad>);
			this._Producto = default(EntityRef<Producto>);
			OnCreated();
		}
		
		[Column(Storage="_ProductoID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ProductoID
		{
			get
			{
				return this._ProductoID;
			}
			set
			{
				if ((this._ProductoID != value))
				{
					if (this._Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProductoIDChanging(value);
					this.SendPropertyChanging();
					this._ProductoID = value;
					this.SendPropertyChanged("ProductoID");
					this.OnProductoIDChanged();
				}
			}
		}
		
		[Column(Storage="_PropiedadID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PropiedadID
		{
			get
			{
				return this._PropiedadID;
			}
			set
			{
				if ((this._PropiedadID != value))
				{
					if (this._Propiedad.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPropiedadIDChanging(value);
					this.SendPropertyChanging();
					this._PropiedadID = value;
					this.SendPropertyChanged("PropiedadID");
					this.OnPropiedadIDChanged();
				}
			}
		}
		
		[Column(Name="Valor", Storage="_Valor1", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Valor1
		{
			get
			{
				return this._Valor1;
			}
			set
			{
				if ((this._Valor1 != value))
				{
					this.OnValor1Changing(value);
					this.SendPropertyChanging();
					this._Valor1 = value;
					this.SendPropertyChanged("Valor1");
					this.OnValor1Changed();
				}
			}
		}
		
		[Association(Name="Propiedad_Valor", Storage="_Propiedad", ThisKey="PropiedadID", IsForeignKey=true)]
		public Propiedad Propiedad
		{
			get
			{
				return this._Propiedad.Entity;
			}
			set
			{
				Propiedad previousValue = this._Propiedad.Entity;
				if (((previousValue != value) 
							|| (this._Propiedad.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Propiedad.Entity = null;
						previousValue.Valors.Remove(this);
					}
					this._Propiedad.Entity = value;
					if ((value != null))
					{
						value.Valors.Add(this);
						this._PropiedadID = value.PropiedadID;
					}
					else
					{
						this._PropiedadID = default(int);
					}
					this.SendPropertyChanged("Propiedad");
				}
			}
		}
		
		[Association(Name="Producto_Valor", Storage="_Producto", ThisKey="ProductoID", IsForeignKey=true)]
		public Producto Producto
		{
			get
			{
				return this._Producto.Entity;
			}
			set
			{
				Producto previousValue = this._Producto.Entity;
				if (((previousValue != value) 
							|| (this._Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Producto.Entity = null;
						previousValue.Valors.Remove(this);
					}
					this._Producto.Entity = value;
					if ((value != null))
					{
						value.Valors.Add(this);
						this._ProductoID = value.ProductoID;
					}
					else
					{
						this._ProductoID = default(int);
					}
					this.SendPropertyChanged("Producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
